cmake_minimum_required(VERSION 3.29)
project(worldchunks VERSION 0.3.1 LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
if(NOT WIN32 AND NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
  message(FATAL_ERROR "Supported platforms: Windows and Linux x86-64.")
endif()
find_package(expected-lite CONFIG REQUIRED)
find_package(funchook CONFIG REQUIRED)
if(NOT WIN32)
  find_package(OpenSSL REQUIRED)
endif()
find_package(nlohmann_json CONFIG REQUIRED)
include(FetchContent)
FetchContent_Declare(endstone GIT_REPOSITORY https://github.com/EndstoneMC/endstone.git
  GIT_TAG 1c71186cba896c5e0bc432384a8a8e72dfb2a626)
FetchContent_MakeAvailable(endstone)
endstone_add_plugin(worldchunks src/plugin.cpp src/native.cpp)
target_include_directories(worldchunks PRIVATE include)
target_link_libraries(worldchunks PRIVATE funchook::funchook nlohmann_json::nlohmann_json ${CMAKE_DL_LIBS})
endstone_add_plugin(worldchunks_optimizer src/optimizer.cpp)
target_include_directories(worldchunks_optimizer PRIVATE include)
target_link_libraries(worldchunks_optimizer PRIVATE nlohmann_json::nlohmann_json ${CMAKE_DL_LIBS})

foreach(target worldchunks worldchunks_optimizer)
  if(WIN32)
    target_compile_definitions(${target} PRIVATE NOMINMAX WIN32_LEAN_AND_MEAN)
    target_link_libraries(${target} PRIVATE advapi32)
    target_compile_options(${target} PRIVATE /W3)
  else()
    get_target_property(libs ${target} LINK_LIBRARIES)
    list(REMOVE_ITEM libs -static-libgcc)
    set_property(TARGET ${target} PROPERTY LINK_LIBRARIES "${libs}")
    target_link_libraries(${target} PRIVATE -shared-libgcc)
    target_compile_options(${target} PRIVATE -Wall -Wextra -Wpedantic)
    target_link_options(${target} PRIVATE "LINKER:--exclude-libs,ALL")
  endif()
  install(TARGETS ${target} LIBRARY DESTINATION plugins RUNTIME DESTINATION plugins)
endforeach()
if(NOT WIN32)
  target_link_libraries(worldchunks PRIVATE OpenSSL::Crypto)
endif()
